### ISSUE TITLE
Зависает без интернета

### ISSUE THREAD

**Issue by mgarna** [TkachenkoMax/ChatApp#1]
При запуске программы в автономном режиме, программа не отвечает ни на какие запросы

**Comment by koha26** [comment]
It is a feature, not a bug. 
Ошибка найдена, т.к. из-за отсутствия интернета невозможно получить список контактов с сервера и поэтому программа зависает.

**Comment by TkachenkoMax** [comment]
@koha26 найдена но не исправлена?)

**Comment by koha26** [comment]
@TkachenkoMax наша команда устраняет эту проблему. Извините за предоставленные неудобства. В ближайшее время все будет исправлено. Будьте с нами. 
P.S. ChatApp2015
